.TH "LIPSUM-PRINT" "1" "March 2014" "lipsum-print 1.0" "User Commands"
.SH "NAME"
lipsum-print
.SH "DESCRIPTION"
.PP
Print some messages using the log middleware.
.SH "USAGE"

\fBlipsum print <args>\fR
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
.SH "COPYRIGHT"
.PP
Copyright (C) 2014 Freeform Systems, Ltd.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
