.TH "LIPSUM-HELP" "1" "March 2014" "lipsum-help 1.0" "User Commands"
.SH "NAME"
lipsum-help
.SH "DESCRIPTION"
.PP
Show help for commands.
.SH "SYNOPSIS"

\fBlipsum help <command>\fR
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
.SH "COPYRIGHT"
.PP
Copyright (C) 2014 Freeform Systems, Ltd.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
