.TH "LIPSUM" "1" "March 2014" "lipsum 1.0" "User Commands"
.SH "NAME"
lipsum
.SH "DESCRIPTION"
.PP
Throw an exception.
.SH "USAGE"

\fBlipsum exception <args>\fR
.SH "BUGS"
.PP
Report bugs to muji noop@xpm.io.
.SH "COPYRIGHT"
.PP
Copyright (C) 2014 Freeform Systems, Ltd.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
